"""Build the Quarto metadata passed to `quarto render --metadata-file`.

Constructed as a dict and dumped as YAML, so that per-render values can be
placed inside the right format block without textual splicing.
"""
from __future__ import annotations

from pathlib import Path

import yaml

from quartocourse import assets
from quartocourse.config import Config

SLIDE_WIDTH = 1400
SLIDE_HEIGHT = 800


def build_brand_css(cfg: Config, dest_dir: Path) -> Path:
    """Generated stylesheet overriding slides.css's custom properties."""
    css = (
        "/* Generated by quartocourse from [brand] in course.toml. */\n"
        ":root {\n"
        f"  --qc-font: {cfg.brand.font};\n"
        f"  --qc-accent: {cfg.brand.accent};\n"
        f"  --qc-body-size: {cfg.brand.body_font_size};\n"
        "}\n"
    )
    dest_dir.mkdir(parents=True, exist_ok=True)
    path = dest_dir / "brand.css"
    path.write_text(css)
    return path


def stage_assets(cfg: Config, dest_dir: Path) -> dict[str, Path]:
    """Materialise every asset Quarto needs, returning paths by role."""
    staged = {
        "slides_css": assets.stage(assets.SLIDES_CSS, dest_dir),
        "reveal_filter": assets.stage(assets.REVEAL_TITLE_SLIDE_LUA, dest_dir),
        "typst_filter": assets.stage(assets.TYPST_FORMAT_LUA, dest_dir),
        "brand_css": build_brand_css(cfg, dest_dir),
    }
    staged["extra_css"] = [assets.stage_external(c, dest_dir) for c in cfg.brand.css]
    return staged


def slides_metadata(cfg: Config, staged: dict, footer_html: str) -> dict:
    css = [staged["slides_css"], staged["brand_css"], *staged["extra_css"]]
    return {
        "format": {
            "revealjs": {
                "width": SLIDE_WIDTH,
                "height": SLIDE_HEIGHT,
                "theme": "default",
                "css": [str(c) for c in css],
                "filters": [str(staged["reveal_filter"])],
                "slide-number": True,
                "transition": "none",
                "code-overflow": "scroll",
                "code-line-numbers": False,
                "embed-resources": True,
                "history": True,
                "hash-type": "number",
                "footer": footer_html,
            }
        },
        "execute": {"enabled": False, "echo": True},
    }


def notes_metadata(cfg: Config, staged: dict, notebook: Path, header: str) -> dict:
    typst: dict = {
        "papersize": "a4",
        "margin": {"x": "2cm", "y": "2cm"},
        "toc": True,
        "number-sections": False,
        "fontsize": "11pt",
        # Routed through include-in-header because Quarto passes that text
        # verbatim, bypassing Pandoc's smart-quote conversion -- which would
        # otherwise mangle the straight quotes inside rgb("#...") and
        # image("...") and produce Typst that will not compile.
        "include-in-header": [{"text": header}],
        "filters": [str(staged["typst_filter"])],
    }
    title = notebook.stem.replace("_", " ")
    subtitle = " — ".join(p for p in (cfg.course.code, cfg.course.title) if p)
    meta: dict = {
        "format": {"typst": typst},
        "execute": {"enabled": False, "echo": True},
        "title": title,
    }
    if subtitle:
        meta["subtitle"] = subtitle
    if cfg.course.author:
        meta["author"] = cfg.course.author
    return meta


def write(meta: dict, dest_dir: Path, name: str) -> Path:
    dest_dir.mkdir(parents=True, exist_ok=True)
    path = dest_dir / name
    path.write_text(yaml.safe_dump(meta, sort_keys=False, default_flow_style=False))
    return path
